### PR TITLE
Remove Bits add Sats + Fix repeated address bug + share sheets (already on develop)

### PR DESCRIPTION
**Pull request by igorgue**
This contains the following changes:

- Removes Bits and MBits
- Adds Satoshi (SAT)
- Fix send screen switch from Fiat Currency to BTC or Satoshi

What's not included:

- Fix sweep private key: Unfortunately, this requires more code, and work will be done in another PR that includes changes for our core library that we forgot to do when renaming the project.

### CODE REVIEW

**Comment by igorgue** [comment]
@arubinofaux & @edgarnet before merging this, we need to make sure I can update the breadwallet-core library with it just like I just did on iOS...

**Comment by edgarnet** [comment]
Updates to the core library build and run as expected.

**Comment by edgarnet** [comment]
There's an issue on my end with BRKey.java: **No implementation found for boolean co.jniwrappers.BRKey.setPrivKey(byte[])**

**Comment by igorgue** [comment]
I’ll check it out. I think I fixed those.

**Comment by igorgue** [comment]
@edgarnet fixed that, thanks!

**Comment by edgarnet** [comment]
Builds and runs as expected on my end.

**Pull request merged**
